project_id = "ytxcrnkzheysmudcfwvm"

[functions.ai-chat]
verify_jwt = false

[functions.ai-categorize]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.ai-receipt]
verify_jwt = false
